<a href="https://colab.research.google.com/github/tuzvebuz/MLAlgorithms/blob/master/MGL_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas


A multidimensional data set is a data frame.
A single dimensional data set is a series object.

## Importing pandas and numpy

Pandas is the focus of this notebook but numpy will be used to initialize arrays.

In [4]:
import pandas as pd
import numpy as np

## Series object

Make a series object with Series(), this takes an array so with numpy we can initialize an array from 1 to 10 with an increasement of 1.

In [65]:
n1 = np.arange(1,10,1)
s1 = pd.Series(n1)

## Series object operations
Same logic but different range and increasement.
However, we also show operations between series objects. s2-s1 will remove object at index 1 in s1 from the object at index 1 in s1. This will continue for each corresponding index. This will continue untill one runs out of indexes, in that case NaN will take its place.

In [67]:
n2 = np.arange(10,100,10)
s2 = pd.Series(n2)
s2 - s1

0     9
1    18
2    27
3    36
4    45
5    54
6    63
7    72
8    81
dtype: int64

## Index and Input alternatives

Indexes can be changed from default 0,1,2.. to any string or number.

In [11]:
s3 = pd.Series(l1, index=['a','b','c','d','e'])
s3

a    4
b    5
c    5
d    6
e    7
dtype: int64

This could be initialized also with a dictionary.

In [12]:
inventory = {"Fords": 20, "Nissans": 45, "Lamborghinis": 3, "Toyota": 200}

s4 = pd.Series(inventory)
s4

Fords            20
Nissans          45
Lamborghinis      3
Toyota          200
dtype: int64

## Data frame object

In [2]:
import kagglehub
path = kagglehub.dataset_download("uciml/iris")

Using Colab cache for faster access to the 'iris' dataset.

In [68]:
candidates = ["Mark", "Bob", "Jan", "Edith"]
marks = [100, 80, 55, 67]
df1 = pd.DataFrame({"Names": candidates, "Marks": marks})
df1

   Names  Marks
0   Mark    100
1    Bob     80
2    Jan     55
3  Edith     67

In [11]:
import os

print(os.listdir(path))


csv_file_path = os.path.join(path, 'Iris.csv')

iris = pd.read_csv(csv_file_path)

iris.iloc[0:10, 0:5]

['Iris.csv', 'database.sqlite']

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2
5   6            5.4           3.9            1.7           0.4
6   7            4.6           3.4            1.4           0.3
7   8            5.0           3.4            1.5           0.2
8   9            4.4           2.9            1.4           0.2
9  10            4.9           3.1            1.5           0.1

In [16]:
iris.loc[0:10, ["Id", "PetalLengthCm"]]

    Id  PetalLengthCm
0    1            1.4
1    2            1.4
2    3            1.3
3    4            1.5
4    5            1.4
5    6            1.7
6    7            1.4
7    8            1.5
8    9            1.4
9   10            1.5
10  11            1.5

In [21]:
iris.drop([1], axis=0) # Axis toggles row or column (possibly also depth)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica